stages:
  - check
  - hil
  - mirror

checks:
  stage: check
  variables:
    UV_FROZEN: "true"
  script:
    - uv run poe checks
    - uv run pytest --junitxml=junit.xml src
    - uv run poe cover
    - uv run coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

hil:
  stage: hil
  script:
    - uv run poe healthcheck
    - uv run poe sensors-test
    - uv run poe integration

mirror:
  stage: mirror
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - git checkout -B main
    - git push --mirror git@github.com:engineering-with-ai/python-circuitpython.git
  only:
    - main
